[package]
name = "you-mod"
version = "0.1.0"
edition = "2024"
description = "A standalone Rust desktop tool that patches the Wand/WeMod Electron app to unlock Pro membership and disable updates."
license = "Apache-2.0"
repository = "https://github.com/k1tbyte/you-mod"

[lib]
crate-type = ["rlib"]
path = "src/lib.rs"

[dependencies]
gpui-kit = "0.7.1"
asar-rust = "0.1.0"
cildec = "0.1.0"
sha2 = "0.11.0"
regex = { version = "1.13.1", default-features = false, features = [
    "std",
    "perf",
] }
anyhow = "1.0.104"
thiserror = "2.0.21"
dirs = "7.0.0"

[dev-dependencies]
tempfile = "3.27.0"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
panic = "abort"
