[package]
name = "version-dll"
version = "0.1.0"
edition = "2024"

[lib]
name = "version"
crate-type = ["cdylib"]

[dependencies]
windows = { version = "0.62", features = [
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_SystemServices",
    "Win32_System_SystemInformation",
] }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
panic = "abort"
